@baseURL = http://localhost:3001

### Simular error de conexión (ECONNREFUSED)
GET {{baseURL}}/api/dimensions?simulate=connection

### Simular error de autenticación (28P01)
GET {{baseURL}}/api/dimensions?simulate=auth

### Simular error de base de datos (3D000)
GET {{baseURL}}/api/dimensions?simulate=database

### Simular error de query SQL (42601)
GET {{baseURL}}/api/dimensions?simulate=query

### Probar ruta inexistente (404)
GET {{baseURL}}/api/ruta-inexistente